### ISSUE TITLE
doesnt work on my machine

### ISSUE THREAD

**Issue by randcn** [slaytr/GameOfLife#1]
im using rhel

**Comment by slaytr** [comment]
Thanks for the feedback, I wrote this a while ago and it was tested exclusively on Ubuntu 16.04 with CUDA 8.0 and a GTX 1050 Ti. I've switched to a RTX 2070 and I'm having some issues with it as well. I'm currently working on other projects and I will likely archive this in the future

**Comment by randcn** [comment]
fix it or ill tell ur progamer team
